// To gerarate more authTokens:
// import { customAlphabet } from 'nanoid';
// const nanoid = customAlphabet('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', 64);
// console.log(`NEST_${nanoid()}`);

export const users = [
  {
    username: 'maximousblk',
    fullName: 'Maximous Black',
    bio: "I'm a Web Developer who likes building beautiful web interfaces & experiences.",
    avatar: 'https://github.com/maximousblk.png',
    authTokens: ['NEST_MKSLUBSNJDRAW60I8LI8QLK3GUUQ5J4VH0SC0WX8INQCZ48OYUULH7Y9YRPXUI5J'],
  },
  {
    username: 'oganexon',
    fullName: 'Maël Acier',
    avatar: 'https://github.com/oganexon.png',
    authTokens: ['NEST_BO4CURUTR467Y5MGL6W39ZX1H3V64BMNBMRKV2H38DV16MZE82A4B7P64BN58JC4'],
  },
  {
    username: 'nestland',
    fullName: 'Nest Land',
    avatar: 'https://github.com/nestdotland.png',
    bio: 'The Nest Authors',
    authTokens: ['NEST_WBFH7VSJUPRT7MI8ICAUE363G5FHY8I9GWY3RMM9P2AUVJR5BAR18BWKWK2I7BNT'],
  },
  {
    username: 'denoland',
    fullName: 'Deno',
    avatar: 'https://github.com/denoland.png',
    bio: 'The Deno Authors',
    authTokens: ['NEST_TN2SHMVBW4R8DB20EVPA5WQFQXGAT1FG8H0BZ8BOTMPCT0VQ69A36XVOZU1JOLMS'],
  },
  {
    username: 'ry',
    fullName: 'Ryan Dahl',
    avatar: 'https://github.com/ry.png',
    bio: 'Creator of NodeJS and Deno',
    authTokens: ['NEST_2NNOSL5YKKJEQR3LY2KWQ2NISH27MFEUA6TMLC8OFAB9L9VDEPKZC12HA9VXXL6N'],
  },
];

export const modules = [
  {
    name: 'std',
    author: 'denoland',
    fullname: 'Standard Library',
    homepage: 'https://deno.land/std',
    contributors: ['ry', 'denoland'],
    src: 'https://deno.land/src@',
    versions: [
      { name: '0.94.0', deps: [], tdeps: [], tpdeps: [] },
      { name: '0.95.0', deps: [], tdeps: [], tpdeps: [] },
      { name: '0.96.0', deps: [], tdeps: [], tpdeps: [] },
      { name: '0.97.0', deps: [], tdeps: [], tpdeps: [] },
      { name: '0.98.0', deps: [], tdeps: [], tpdeps: [] },
      { name: '0.99.0', deps: [], tdeps: [], tpdeps: [] },
    ],
    tags: [
      {
        name: 'latest',
        version: '0.99.0',
      },
    ],
    devConfig: {
      ignore: [],
    },
    publishConfig: {
      main: '',
      bin: [],
    },
    files: [
      'LICENSE',
      'README.md',
      'flags/mod.ts',
      'fmt/colors.ts',
      'fmt/printf.ts',
      'mime/mod.ts',
      'mime/multipart.ts',
      'mime/test.ts',
      'uuid/mod.ts',
      'uuid/v1.ts',
      'uuid/v4.ts',
      'uuid/v5.ts',
      'version.ts',
      'ws/mod.ts',
      'ws/test.ts',
    ],
  },
  {
    name: 'nest',
    author: 'nestland',
    fullname: 'Nest CLI',
    homepage: 'https://nest.land/-/nest',
    contributors: ['oganexon', 'maximousblk', 'nestland'],
    src: 'https://github.com/nestdotland/nest/raw/',
    versions: [
      {
        name: '0.1.3',
        deps: [{ author: 'denoland', name: 'std', version: '0.94.0' }],
        tdeps: [],
        tpdeps: [],
      },
      {
        name: '0.1.4',
        deps: [{ author: 'denoland', name: 'std', version: '0.95.0' }],
        tdeps: [],
        tpdeps: [],
      },
      {
        name: '0.1.5',
        deps: [{ author: 'denoland', name: 'std', version: '0.95.0' }],
        tdeps: [],
        tpdeps: [],
      },
      {
        name: '0.1.6',
        deps: [{ author: 'denoland', name: 'std', version: '0.96.0' }],
        tdeps: [],
        tpdeps: [],
      },
      {
        name: '0.1.7',
        deps: [{ author: 'denoland', name: 'std', version: '0.97.0' }],
        tdeps: [],
        tpdeps: [],
      },
      {
        name: '0.1.8',
        deps: [{ author: 'denoland', name: 'std', version: '0.99.0' }],
        tdeps: [],
        tpdeps: [],
      },
    ],
    tags: [
      {
        name: 'latest',
        version: '0.1.8',
      },
      {
        name: 'alpha',
        version: '0.1.8',
      },
    ],
    devConfig: {
      ignore: ['tests'],
    },
    publishConfig: {
      main: 'mod.ts',
      bin: ['nest.ts'],
    },
    files: [
      'LICENSE',
      'README.md',
      'mod.ts',
      'nest.ts',
      'src/cli/commands/help.ts',
      'src/cli/commands/init.ts',
      'src/cli/commands/login.ts',
      'src/cli/commands/logout.ts',
      'src/cli/commands/publish.ts',
      'src/cli/commands/setup.ts',
      'src/cli/commands/switch.ts',
      'src/cli/commands/sync.ts',
      'src/cli/commands/upgrade.ts',
      'src/version.ts',
    ],
  },
  {
    name: 'eggs',
    author: 'nestland',
    fullname: 'Eggs CLI',
    homepage: 'https://nest.land/-/eggs',
    contributors: ['oganexon', 'maximousblk', 'nestland'],
    src: 'https://github.com/nestdotland/eggs/raw/',
    versions: [
      {
        name: '0.2.3',
        deps: [{ author: 'denoland', name: 'std', version: '0.94.0' }],
        tdeps: [{ author: 'nestland', name: 'nest', version: '0.1.8', tag: 'alpha' }],
        tpdeps: [],
      },
      {
        name: '0.2.4',
        deps: [{ author: 'denoland', name: 'std', version: '0.94.0' }],
        tdeps: [{ author: 'nestland', name: 'nest', version: '0.1.8', tag: 'alpha' }],
        tpdeps: [],
      },
      {
        name: '0.2.5',
        deps: [{ author: 'denoland', name: 'std', version: '0.94.0' }],
        tdeps: [{ author: 'nestland', name: 'nest', version: '0.1.8', tag: 'alpha' }],
        tpdeps: [],
      },
      {
        name: '0.3.1',
        deps: [{ author: 'denoland', name: 'std', version: '0.94.0' }],
        tdeps: [{ author: 'nestland', name: 'nest', version: '0.1.8', tag: 'alpha' }],
        tpdeps: [],
      },
      {
        name: '0.3.2',
        deps: [{ author: 'denoland', name: 'std', version: '0.94.0' }],
        tdeps: [{ author: 'nestland', name: 'nest', version: '0.1.8', tag: 'alpha' }],
        tpdeps: [],
      },
    ],
    tags: [
      {
        name: 'latest',
        version: '0.3.2',
      },
      {
        name: 'v0',
        version: '0.3.2',
      },
      {
        name: 'v0.2',
        version: '0.2.5',
      },
    ],
    devConfig: {
      ignore: ['tests'],
    },
    publishConfig: {
      main: 'mod.ts',
      bin: ['eggs.ts', 'eggx.ts'],
    },
    files: [
      'README.md',
      'src/keyfile.ts',
      'src/utilities/environment.ts',
      'src/utilities/json.ts',
      'src/utilities/log.ts',
      'src/utilities/types.ts',
      'src/commands.ts',
      'src/commands/upgrade.ts',
      'src/commands/info.ts',
      'src/commands/link.ts',
      'src/commands/update.ts',
      'src/commands/publish.ts',
      'src/commands/init.ts',
      'src/commands/install.ts',
      'src/schema.json',
      'src/version.ts',
      'eggs.ts',
      'eggx.ts',
      'LICENSE',
      'deps.ts',
    ],
  },
  {
    name: 'serve',
    author: 'maximousblk',
    fullname: 'Static File Server',
    homepage: 'https://nest.land/x/maximousblk/serve',
    contributors: ['maximousblk', 'oganexon'],
    src: 'https://github.com/maximousblk/serve/raw/',
    versions: [
      {
        name: '1.0.0',
        deps: [{ author: 'denoland', name: 'std', version: '0.94.0' }],
        tdeps: [],
        tpdeps: [],
      },
      {
        name: '1.0.1',
        deps: [{ author: 'denoland', name: 'std', version: '0.94.0' }],
        tdeps: [],
        tpdeps: [],
      },
      {
        name: '1.0.2',
        deps: [{ author: 'denoland', name: 'std', version: '0.95.0' }],
        tdeps: [],
        tpdeps: [],
      },
      {
        name: '1.0.3',
        deps: [{ author: 'denoland', name: 'std', version: '0.96.0' }],
        tdeps: [],
        tpdeps: [],
      },
      {
        name: '1.0.5',
        deps: [{ author: 'denoland', name: 'std', version: '0.96.0' }],
        tdeps: [],
        tpdeps: [],
      },
    ],
    tags: [],
    devConfig: {
      ignore: [],
    },
    publishConfig: {
      bin: ['serve.ts'],
    },
    files: [
      'serve.ts',
      'deps.ts',
      'src/pages/dir.ts',
      'src/pages/err.ts',
      'src/utils/html.ts',
      'src/utils/server.ts',
      'src/utils/types.ts',
      'README.md',
      'LICENSE',
    ],
  },
  {
    name: 'ghlog',
    author: 'maximousblk',
    fullname: 'GitHub Release Notes Generator',
    homepage: 'https://deno.land/x/ghlog',
    contributors: ['maximousblk'],
    src: 'https://deno.land/x/serve@',
    versions: [
      {
        name: '0.1.0',
        deps: [{ author: 'denoland', name: 'std', version: '0.94.0' }],
        tdeps: [],
        tpdeps: [{ host: 'cdn.skypack.dev', path: '@octokit/core@^3.1.0' }],
      },
      {
        name: '0.1.1',
        deps: [{ author: 'denoland', name: 'std', version: '0.94.0' }],
        tdeps: [],
        tpdeps: [{ host: 'cdn.skypack.dev', path: '@octokit/core@^3.1.0' }],
      },
      {
        name: '0.1.2',
        deps: [{ author: 'denoland', name: 'std', version: '0.95.0' }],
        tdeps: [],
        tpdeps: [{ host: 'cdn.skypack.dev', path: '@octokit/core@^3.1.0' }],
      },
      {
        name: '0.1.3',
        deps: [{ author: 'denoland', name: 'std', version: '0.96.0' }],
        tdeps: [],
        tpdeps: [{ host: 'cdn.skypack.dev', path: '@octokit/core@^3.1.1' }],
      },
      {
        name: '0.2.0',
        deps: [{ author: 'denoland', name: 'std', version: '0.96.0' }],
        tdeps: [],
        tpdeps: [{ host: 'cdn.skypack.dev', path: '@octokit/core@^3.1.1' }],
      },
      {
        name: '0.2.1',
        deps: [{ author: 'denoland', name: 'std', version: '0.96.0' }],
        tdeps: [],
        tpdeps: [{ host: 'cdn.skypack.dev', path: '@octokit/core@^3.2.0' }],
      },
      {
        name: '0.3.0',
        deps: [{ author: 'denoland', name: 'std', version: '0.97.0' }],
        tdeps: [],
        tpdeps: [{ host: 'cdn.skypack.dev', path: '@octokit/core@^3.2.0' }],
      },
      {
        name: '0.3.1',
        deps: [{ author: 'denoland', name: 'std', version: '0.98.0' }],
        tdeps: [],
        tpdeps: [{ host: 'cdn.skypack.dev', path: '@octokit/core@^3.2.0' }],
      },
      {
        name: '0.3.2',
        deps: [{ author: 'denoland', name: 'std', version: '0.98.0' }],
        tdeps: [],
        tpdeps: [{ host: 'cdn.skypack.dev', path: '@octokit/core@^3.2.1' }],
      },
    ],
    tags: [],
    devConfig: {
      ignore: [],
    },
    publishConfig: {
      main: 'mod.ts',
      bin: ['ghlog.ts'],
    },
    files: [
      'examples/basic.ts',
      'examples/deno.ts',
      'examples/yargs.ts',
      'ghlog.ts',
      'mod.ts',
      'src/deps.ts',
      'src/main.ts',
      'src/utils.ts',
    ],
  },
];
