name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Database Dump
        run: ./dump.sh

      - name: Build and push Docker image
        run: docker build .
