name: Lint

on:
  push:
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check Formating
        run: yarn fmt
